[build]
  command = "bun run build"
  publish = "dist/client"

[[redirects]]
  from = "/pdfs/*"
  to = "/pdfs/:splat"
  status = 200
  force = false

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
