/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorksRouteImport } from './routes/works'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorksIndexRouteImport } from './routes/works.index'
import { Route as WorksWorkshopsRouteImport } from './routes/works.workshops'
import { Route as WorksSolutionsRouteImport } from './routes/works.solutions'
import { Route as WorksReportsRouteImport } from './routes/works.reports'
import { Route as WorksPresentationsRouteImport } from './routes/works.presentations'
import { Route as WorksDesignsRouteImport } from './routes/works.designs'

const WorksRoute = WorksRouteImport.update({
  id: '/works',
  path: '/works',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorksIndexRoute = WorksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorksRoute,
} as any)
const WorksWorkshopsRoute = WorksWorkshopsRouteImport.update({
  id: '/workshops',
  path: '/workshops',
  getParentRoute: () => WorksRoute,
} as any)
const WorksSolutionsRoute = WorksSolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => WorksRoute,
} as any)
const WorksReportsRoute = WorksReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => WorksRoute,
} as any)
const WorksPresentationsRoute = WorksPresentationsRouteImport.update({
  id: '/presentations',
  path: '/presentations',
  getParentRoute: () => WorksRoute,
} as any)
const WorksDesignsRoute = WorksDesignsRouteImport.update({
  id: '/designs',
  path: '/designs',
  getParentRoute: () => WorksRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/resources': typeof ResourcesRoute
  '/works': typeof WorksRouteWithChildren
  '/works/designs': typeof WorksDesignsRoute
  '/works/presentations': typeof WorksPresentationsRoute
  '/works/reports': typeof WorksReportsRoute
  '/works/solutions': typeof WorksSolutionsRoute
  '/works/workshops': typeof WorksWorkshopsRoute
  '/works/': typeof WorksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/resources': typeof ResourcesRoute
  '/works/designs': typeof WorksDesignsRoute
  '/works/presentations': typeof WorksPresentationsRoute
  '/works/reports': typeof WorksReportsRoute
  '/works/solutions': typeof WorksSolutionsRoute
  '/works/workshops': typeof WorksWorkshopsRoute
  '/works': typeof WorksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/resources': typeof ResourcesRoute
  '/works': typeof WorksRouteWithChildren
  '/works/designs': typeof WorksDesignsRoute
  '/works/presentations': typeof WorksPresentationsRoute
  '/works/reports': typeof WorksReportsRoute
  '/works/solutions': typeof WorksSolutionsRoute
  '/works/workshops': typeof WorksWorkshopsRoute
  '/works/': typeof WorksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/resources'
    | '/works'
    | '/works/designs'
    | '/works/presentations'
    | '/works/reports'
    | '/works/solutions'
    | '/works/workshops'
    | '/works/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/resources'
    | '/works/designs'
    | '/works/presentations'
    | '/works/reports'
    | '/works/solutions'
    | '/works/workshops'
    | '/works'
  id:
    | '__root__'
    | '/'
    | '/resources'
    | '/works'
    | '/works/designs'
    | '/works/presentations'
    | '/works/reports'
    | '/works/solutions'
    | '/works/workshops'
    | '/works/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ResourcesRoute: typeof ResourcesRoute
  WorksRoute: typeof WorksRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/works': {
      id: '/works'
      path: '/works'
      fullPath: '/works'
      preLoaderRoute: typeof WorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/works/': {
      id: '/works/'
      path: '/'
      fullPath: '/works/'
      preLoaderRoute: typeof WorksIndexRouteImport
      parentRoute: typeof WorksRoute
    }
    '/works/workshops': {
      id: '/works/workshops'
      path: '/workshops'
      fullPath: '/works/workshops'
      preLoaderRoute: typeof WorksWorkshopsRouteImport
      parentRoute: typeof WorksRoute
    }
    '/works/solutions': {
      id: '/works/solutions'
      path: '/solutions'
      fullPath: '/works/solutions'
      preLoaderRoute: typeof WorksSolutionsRouteImport
      parentRoute: typeof WorksRoute
    }
    '/works/reports': {
      id: '/works/reports'
      path: '/reports'
      fullPath: '/works/reports'
      preLoaderRoute: typeof WorksReportsRouteImport
      parentRoute: typeof WorksRoute
    }
    '/works/presentations': {
      id: '/works/presentations'
      path: '/presentations'
      fullPath: '/works/presentations'
      preLoaderRoute: typeof WorksPresentationsRouteImport
      parentRoute: typeof WorksRoute
    }
    '/works/designs': {
      id: '/works/designs'
      path: '/designs'
      fullPath: '/works/designs'
      preLoaderRoute: typeof WorksDesignsRouteImport
      parentRoute: typeof WorksRoute
    }
  }
}

interface WorksRouteChildren {
  WorksDesignsRoute: typeof WorksDesignsRoute
  WorksPresentationsRoute: typeof WorksPresentationsRoute
  WorksReportsRoute: typeof WorksReportsRoute
  WorksSolutionsRoute: typeof WorksSolutionsRoute
  WorksWorkshopsRoute: typeof WorksWorkshopsRoute
  WorksIndexRoute: typeof WorksIndexRoute
}

const WorksRouteChildren: WorksRouteChildren = {
  WorksDesignsRoute: WorksDesignsRoute,
  WorksPresentationsRoute: WorksPresentationsRoute,
  WorksReportsRoute: WorksReportsRoute,
  WorksSolutionsRoute: WorksSolutionsRoute,
  WorksWorkshopsRoute: WorksWorkshopsRoute,
  WorksIndexRoute: WorksIndexRoute,
}

const WorksRouteWithChildren = WorksRoute._addFileChildren(WorksRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ResourcesRoute: ResourcesRoute,
  WorksRoute: WorksRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
